"""patient assignments

Revision ID: 0dba1aa0cf1f
Revises: ebac5a8d9572
Create Date: 2026-07-18 12:08:38.408687
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0dba1aa0cf1f'
down_revision: Union[str, None] = 'ebac5a8d9572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'user_id', name='uq_patient_user')
    )
    op.create_index(op.f('ix_patient_assignments_patient_id'), 'patient_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_assignments_user_id'), 'patient_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_assignments_user_id'), table_name='patient_assignments')
    op.drop_index(op.f('ix_patient_assignments_patient_id'), table_name='patient_assignments')
    op.drop_table('patient_assignments')
    # ### end Alembic commands ###
